name: Update Game Links

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Fetch and Compare
        run: python scripts/fetch_links.py

      - name: Commit and Push
        run: |
          if [ -z "$COMMIT_MSG" ]; then
            echo "没有任何变动。"
          else
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add links/*.json

            BEIJING_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')
            git commit -m "更新: $COMMIT_MSG $BEIJING_TIME UTC+8"
            git pull --rebase origin main
            git push origin main
          fi
